
name: e2e

on:
  pull_request:
    # for testing purposes
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Install Dependency
        run: |
          npm install -g firebase-tools
          npm install
      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          start: npm run server, npm run start
          browser: chrome
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
        env:
          # Branch settings
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_REF: ${{ github.ref }}
          # Service Account (used for creating custom auth tokens)
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          # UID of User to login as during tests
          CYPRESS_TEST_UID: ${{ secrets.TEST_UID }}
          TEST_UID: ${{ secrets.TEST_UID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          # rest
          REACT_APP_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          REACT_APP_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          REACT_APP_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          REACT_APP_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          CYPRESS_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          CYPRESS_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          CYPRESS_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          CYPRESS_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          CYPRESS_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          CYPRESS_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          CYPRESS_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          CYPRESS_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
