name: CI

on:
  push:
    # for testing purposes
    branches: [main]
  pull_request:
    # for testing purposes
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          start: npm run server, npm run start
          browser: chrome
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
        env:
          # Branch settings
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_REF: ${{ github.ref }}
         
