name: e2e

on:
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          start: npm run server, npm run start
          browser: chrome
          wait-on: http://localhost:3000
          wait-on-timeout: 120
          config: CYPRESS_FIREBASE_API_KEY=AIzaSyB3ZYZeViWedCfDr24dmmw2V0ADxgFU6fs,CYPRESS_FIREBASE_AUTH_DOMAIN=hellobeer-32e73.firebaseapp.com,CYPRESS_FIREBASE_PROJECT_ID=hellobeer-32e73,CYPRESS_FIREBASE_STORAGE_BUCKET=hellobeer-32e73.appspot.com,CYPRESS_FIREBASE_MESSAGING_SENDER_ID=445462528668,CYPRESS_FIREBASE_MEASUREMENT_ID=G-VP1X19ENCT,CYPRESS_FIREBASE_APP_ID=1:445462528668:web:56567577a0d6973c51a359
        env:
          # Branch settings
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_REF: ${{ github.ref }}
          # Service Account (used for creating custom auth tokens)
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          # UID of User to login as during tests
          CYPRESS_TEST_UID: ${{ secrets.TEST_UID }}
          # rest
          REACT_APP_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          REACT_APP_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
