name: e2e

on:
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          start: npm run server, npm run start
          browser: chrome
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_REF: ${{ github.ref }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          CYPRESS_TEST_UID: ${{ secrets.TEST_UID }}
          REACT_APP_API_KEY: AIzaSyB3ZYZeViWedCfDr24dmmw2V0ADxgFU6fs
          REACT_APP_AUTH_DOMAIN: hellobeer-32e73.firebaseapp.com
          REACT_APP_PROJECT_ID: hellobeer-32e73
          REACT_APP_STORAGE_BUCKET: hellobeer-32e73.appspot.com
          REACT_APP_MESSAGING_SENDER_ID: 445462528668
          REACT_APP_MEASUREMENT_ID: G-VP1X19ENCT
          REACT_APP_APP_ID: 1:445462528668:web:56567577a0d6973c51a359
